# Generated by Django 2.0 on 2020-06-19 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report_form',
            name='link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='patient_details.patient_appointment'),
        ),
    ]
