# Generated by Django 2.0 on 2020-06-15 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient_login', '0004_auto_20200614_1140'),
    ]

    operations = [
        migrations.CreateModel(
            name='patient_appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('date_of_appointment', models.CharField(max_length=15)),
                ('time_of_appointment', models.CharField(max_length=15)),
                ('problem', models.CharField(max_length=200)),
                ('status', models.CharField(default='pending', max_length=15)),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='patient_login.patient_login')),
            ],
        ),
    ]
