# Generated by Django 2.0 on 2020-06-15 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient_login', '0004_auto_20200614_1140'),
        ('patient_details', '0002_patient_appointment_fees'),
    ]

    operations = [
        migrations.CreateModel(
            name='patient_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.CharField(max_length=10)),
                ('weight', models.CharField(max_length=10)),
                ('blood_group', models.CharField(max_length=10)),
                ('previous_problem', models.CharField(max_length=10)),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='patient_login.patient_login')),
            ],
        ),
    ]
