# Generated by Django 2.0 on 2020-06-15 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_details', '0003_patient_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_history',
            name='status',
            field=models.CharField(default='filled', max_length=15),
        ),
    ]
