# Generated by Django 2.0 on 2020-06-17 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_details', '0004_patient_history_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_appointment',
            name='doctor_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='patient_appointment',
            name='field',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
