# Generated by Django 2.0 on 2020-06-17 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_details', '0005_auto_20200617_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_appointment',
            name='message',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
