# Generated by Django 2.0 on 2020-06-18 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_details', '0006_patient_appointment_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_appointment',
            name='fees',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
