# Generated by Django 2.0 on 2020-06-13 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_login', '0002_auto_20200612_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor_login',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
