# Generated by Django 2.0 on 2020-06-16 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_login', '0004_doctor_degree_specialization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor_degree',
            name='degree',
            field=models.CharField(max_length=50),
        ),
    ]
