# Generated by Django 2.0 on 2020-06-16 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_login', '0006_doctor_login_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor_login',
            name='doctor_degree',
            field=models.CharField(max_length=50),
        ),
    ]
