# Generated by Django 2.0 on 2020-06-14 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='patient_login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=35, unique=True)),
                ('password', models.CharField(max_length=10)),
                ('mobile_no', models.CharField(max_length=10)),
                ('age', models.CharField(max_length=5)),
                ('gender', models.CharField(max_length=10)),
            ],
        ),
    ]
