# Generated by Django 2.0 on 2020-06-14 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_login',
            name='password',
            field=models.CharField(max_length=15),
        ),
    ]
