# Generated by Django 2.0 on 2020-06-14 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_login', '0002_auto_20200614_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_login',
            name='email',
            field=models.CharField(max_length=35),
        ),
    ]
