# Generated by Django 2.0 on 2020-06-20 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_login', '0004_auto_20200614_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_login',
            name='finished_appointment_count',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
