# Generated by Django 2.0 on 2020-06-20 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient_login', '0005_patient_login_finished_appointment_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient_login',
            name='finished_appointment_count',
        ),
    ]
